### ISSUE TITLE
Where are the binaries

### ISSUE THREAD

**Issue by Umar-Ayub** [BII-wushuang/FLLIT#1]
Hello, I cloned this repository to try out FLLIT however I can't locate the runtime libraries mentioned in 'FLLIT/Compiled' folder. Where could I get those? Would this be compatible with MATLAB R2018b or on any other OS such as windows?

**Comment by BII-wushuang** [comment]
Hi, the [MATLAB Runtime libraries](http://ssd.mathworks.com/supportfiles/downloads/R2016a/deployment_files/R2016a/installers/glnxa64/MCR_R2016a_glnxa64_installer.zip) have to be downloaded and extracted to the compiled folder. They were not included in the repository due to file size restrictions. The installation instructions are given [here](https://github.com/BII-wushuang/FLLIT#getting-started-with-fllit).

#### Compatibility
FLLIT is unfortunately incompatible with Windows or MacOS at the moment since it depends on some C++ MEX binaries compiled for Linux only. 

FLLIT is compatible and tested on Ubuntu 16.04 and Ubuntu 18.04 operating systems. The  [MATLAB Runtime libraries](http://ssd.mathworks.com/supportfiles/downloads/R2016a/deployment_files/R2016a/installers/glnxa64/MCR_R2016a_glnxa64_installer.zip) need to be installed to run the **precompiled FLLIT**.

If you do have access to MATLAB (tested for version >=R2016a) installed on a Ubuntu OS, you can simply run [FLLIT.m](../tree/master/src/FLLIT.m) in MATLAB.

**Comment by ZhenguangLiu** [comment]
This is a good project
